- name: Install Javascript linters
  npm: name={{item}} global=yes state=latest
  with_items:
    - jshint
    - eslint
    - jscs
    - standard
    - semistandard
  tags:
    - npm
- name: Install Closure linter
  pip: name={{item}} state=latest extra_args={{python_pip_extra_args}}
  with_items:
    - http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz
  tags:
    - pip
