This appendix provides a comprehensive changelog of all releases:

@menu
* master        :: unreleased
* 0.13          :: Jun 28, 2013
* 0.12          :: May 18, 2013
* 0.11          :: May 01, 2013
* 0.10          :: Apr 21, 2013
* 0.9           :: Apr 13, 2013
* 0.8           :: Apr 09, 2013
* 0.7.1         :: Feb 23, 2013
* 0.7           :: Feb 14, 2013
* 0.6.1         :: Jan 30, 2013
* 0.6           :: Jan 29, 2013
* 0.5           :: Dec 28, 2012
* 0.4           :: Nov 21, 2012
* 0.3           :: Oct 20, 2012
* 0.2           :: Oct 15, 2012
* 0.1           :: Oct 11, 2012
@end menu

@macro ghissue{number, text}
@gh{lunaryorn/flycheck/issues/\number\, \text\}
@end macro

@node 0.1, 0.2, , Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.1 (Oct 11, 2012)

Initial release as flymake-checkers

@itemize @bullet
@item
New syntax checkers

@itemize @bullet
@item
TeX/LaTeX
@item
Shell scripts
@item
Python
@item
Ruby
@item
Coffeescript
@item
Emacs Lisp
@end itemize

@end itemize


@node 0.2, 0.3, 0.1, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.2 (Oct 15, 2012)

@itemize @bullet
@item
New syntax checkers

@itemize @bullet
@item
PHP
@end itemize

@item
API changes

@itemize @bullet
@item
@ghissue{2, Simplify syntax checker declarations}
@end itemize

@end itemize

@node 0.3, 0.4, 0.2, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.3 (Oct 20, 2012)

@itemize @bullet
@item
@ghissue{4, Replace @code{flymake-mode} with a custom syntax checking
minor mode}
@end itemize

@node 0.4, 0.5, 0.3, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.4 (Nov 21, 2012)

@itemize @bullet
@item
@ghissue{5, Rename the project to Flycheck}
@item
New syntax checkers

@itemize @bullet
@item
@ghissue{9, HAML}
@item
@ghissue{9, CSS}
@item
@ghissue{9, Javascript with @command{jsl}}
@item
@ghissue{16, Javascript with @command{jshint}}
@item
@ghissue{12, JSON}
@item
LaTeX with @command{lacheck}
@end itemize

@item
Bug fixes
@itemize @bullet
@item
@ghissue{10, Fix type error when checking compressed Emacs Lisp}
@end itemize

@end itemize

@node 0.5, 0.6, 0.4, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.5 (Dec 28, 2012)

@itemize @bullet
@item
New syntax checkers:

@itemize
@item
@ghissue{15, SASS}
@item
@ghissue{21, Perl}
@item
XML
@item
@ghissue{30, Lua}
@end itemize

@item
New features:

@itemize @bullet
@item
@ghissue{25, Support manual buffer-local selection of syntax checker}
@item
@ghissue{28, Add customizable error indicators}
@item
@ghissue{27, Echo error messages at point without 3rd-party libraries
like flymake-cursor}
@end itemize

@item
Improvements:

@itemize @bullet
@item
@ghissue{24, Remember the last automatically selected syntax checker}
@end itemize

@item
Bug fixes:

@itemize @bullet
@item
@ghissue{19, Fix syntax checking of buffers without backing files}
@end itemize

@item
API changes:

@itemize @bullet
@item
@ghissue{15, Replace underlying Flymake API with a custom syntax
checking implementation}
@end itemize

@end itemize

@node 0.6, 0.6.1, 0.5, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.6 (Jan 29, 2013)

@itemize @bullet
@item
New syntax checkers:

@itemize @bullet
@item
@ghissue{53, Emacs Lisp with @code{checkdoc-current-buffer}}
@item
@ghissue{72, PHP with PHP CodeSniffer}
@end itemize

@item
Removed syntax checkers:

@itemize
@item
Javascript with @command{jsl}
@end itemize

@item
New features:

@itemize @bullet
@item
@ghissue{26, Error navigation with @code{next-error} and
@code{previous-error}}
@item
@ghissue{33, Fringe icons instead of error indicators}
@item
@ghissue{59, Menu entry for Flycheck}
@item
@ghissue{35, Customizable error highlighting@comma{} taking the column
number into account}
@item
Configuration files for syntax checkers
@item
Add configuration file support to the syntax checkers
@code{coffee-coffeelint}, @code{html-tidy}, @code{javascript-jshint},
@code{pyton-flake8} and @code{tex-chktex}
@item
@ghissue{58, Allow to compile a buffer with a syntax checker for testing
purposes}
@item
@ghissue{31, Use multiple syntax checkers during a syntax check}
@item
@ghissue{52, Add dedicated help for syntax checkers}
@end itemize

@item
Improvements:

@itemize @bullet
@item
@ghissue{55, Match error patterns in order of declaration}
@end itemize

@item
Bug fixes:

@itemize @bullet
@item
@ghissue{24, Inherit highlighting faces from built-in faces}
@item
@ghissue{36, Correct error patterns of the HTML syntax checker}
@item
@ghissue{42, Detect syntax errors in the @code{python-flake8} syntax
checker}
@item
Fix various regressions after introducing unit tests
@item
@ghissue{45, Inhibit syntax checking during package installation}
@item
@ghissue{54, Disable syntax checking in Tramp buffers}
@item
@ghissue{65, Preserve whitespace in error messages}
@end itemize

@item
API changes:
@itemize
@item
@ghissue{41, Replace syntax checker variables with syntax checker
declarations}
@item
@ghissue{38, Support parsing errors with arbitrary functions instead of
error patterns}
@item
@ghissue{38, Add an error parser for Checkstyle-like XML output}
@end itemize

@end itemize

@node 0.6.1, 0.7, 0.6, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.6.1 (Jan 30, 2013)

@itemize @bullet
@item
Fix package dependencies
@end itemize

@node 0.7, 0.7.1, 0.6.1, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.7 (Feb 14, 2013)

@itemize @bullet
@item
New features:

@itemize @bullet
@item
Navigate to source of syntax checker declarations from syntax checker
help
@item
@ghissue{60, Add online Info manual}
@end itemize

@item
Improvements:

@itemize @bullet
@item
Use pipes instead of TTYs to read output from syntax checkers
@item
@ghissue{80, Defer syntax checks for invisible buffers}
@item
@ghissue{62, Immediately display error messages after error navigation}
@end itemize

@item
Bug fixes:

@itemize @bullet
@item
Never select deleted buffers
@item
Do not let the debugger interfere with necessary cleanup actions
@item
@ghissue{78, Do not attempt to parse empty XML trees}
@item
@ghissue{81, Fix infinite recursion on Windows}
@end itemize

@end itemize

@node 0.7.1, 0.8, 0.7, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.7.1 (Feb 23, 2013)

@itemize @bullet
@item
Bug fixes:

@itemize @bullet
@item
@ghissue{87, Do not signal errors from @code{flycheck-mode}}
@item
Correctly fall back to @env{HOME} when searching configuration files
@item
Correctly ascend to parent directory when searching configuration files
@end itemize

@item
API changes:

@itemize @bullet
@item
Rename @code{config} cell to @code{config-file}
@item
Allow to pass the result of @code{config-file} cells as single argument
@item
@ghissue{86, Add support for evaluating Lisp forms in syntax checker
commands}
@end itemize

@end itemize

@node 0.8, 0.9, 0.7.1, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.8 (Apr 9, 2013)

@itemize @bullet
@item
New syntax checkers:

@itemize @bullet
@item
@ghissue{91, Go using @command{gofmt}}
@item
@ghissue{101, Rust using @command{rustc}}
@end itemize

@item
New features:

@itemize @bullet
@item
@ghissue{29, Add a global Flycheck mode}.  @code{(global-flycheck-mode)}
is now the recommended way to enable Flycheck
@item
@ghissue{72, Add support for syntax checker options}
@item
Add option for the coding standard used by the @code{php-phpcs} syntax
checker
@item
Add options for the maximum McCabe complexity and the maximum line
length to @code{python-flake8}
@end itemize

@item
Improvements:

@itemize @bullet
@item
Support McCabe warnings in @code{python-flake8}
@item
Support warnings from @command{flake8} 2
@item
@ghissue{94, Show long error messages in a popup buffer}
@item
@ghissue{96, Show all error messages at point}
@item
@ghissue{98, Add support for naming warings from @command{flake8} 2}
@item
Flycheck mode is not longer enabled for buffers whose names start with a
space
@item
@ghissue{100, Improve highlighting to reduce screen flickering}
@end itemize

@end itemize

@node 0.9, 0.10, 0.8, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.9 (Apr 13, 2013)

@itemize @bullet
@item
New syntax checkers:

@itemize @bullet
@item
@ghissue{103, SCSS using @command{scss}}
@item
RST (ReStructuredText) using Docutils
@item
@ghissue{107, Go using @command{go build} and @command{go test}}
@end itemize

@item
Improvements:

@itemize @bullet
@item
Quit the error message window when navigating away from error locations
@end itemize

@end itemize

@node 0.10, 0.11, 0.9, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.10 (Apr 21, 2013)

@itemize @bullet
@item
Flycheck uses @ref{Top, , cl-lib, cl} now.  This library is built-in as
of GNU Emacs 24.3.  For earlier releases of GNU Emacs 24 an additional
compatibility library will be installed from GNU ELPA.

@item
New syntax checkers:

@itemize @bullet
@item
@ghissue{112, POSIX Shell script using @command{bash}}
@item
@ghissue{113, Ruby using @command{rubocop}}
@item
@ghissue{108, Elixir}
@item
@ghissue{122, Erlang}
@end itemize

@item
Removed syntax checkers:

@itemize @bullet
@item
@ghissue{115, Python using Pyflakes}.  Use the superior Flake8 syntax
checker
@end itemize

@item
New features:

@itemize @bullet
@item
Add @code{flycheck-copy-messages-as-kill}, mapped to @kbd{C-c ! C-w}, to
copy all error messages under point into kill ring
@item
Add @code{flycheck-google-messages}, mapped to @kbd{C-c ! /}, to google
for error messages under point.  Needs the
@uref{https://github.com/Bruce-Connor/emacs-google-this, Google This}
library
@item
Syntax checkers can redirect output to a temporary directory now using
the @code{temporary-directory} argument symbol
@end itemize

@item
Improvements:

@itemize @bullet
@item
Call option filters for @code{nil} values, too
@item
@ghissue{112, Improve error parsing in Bash syntax checker}
@item
Error navigation does not cross restrictions in narrowed buffers anymore
@item
@ghissue{99, Try to preserve the non-directory part of the buffer's file
name when substituting the @code{source} symbol}
@end itemize

@item
Bug fixes:

@itemize @bullet
@item
Fix error highlighting and navigation in narrowed buffers
@item
@ghissue{118, Use a hopefully more reliable way to parse output of PHP
CodeSniffer}
@end itemize

@end itemize

@node 0.11, 0.12, 0.10, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.11 (May 01, 2013)

@itemize @bullet
@item
New syntax checkers:

@itemize @bullet
@item
@ghissue{124, Scala}
@end itemize

@item
New features:

@itemize @bullet
@item
Customizable error indication with control of the fringe side, via
@code{flycheck-indication-mode}
@item
@ghissue{128, Customizable automatic syntax checking@comma{} via
@code{flycheck-check-syntax-automatically}}
@item
@ghissue{133, Customizable configuration file search@comma{} via
@code{flycheck-locate-config-file-functions}}
@item
Find configuration files in @uref{https://github.com/bbatsov/projectile,
Projectile} projects
@item
Add @code{flycheck-before-syntax-check-hook} and
@code{flycheck-syntax-check-failed-hook}
@end itemize

@item
Improvements:

@itemize @bullet
@item
@ghissue{123, The @code{ruby} syntax checker now differentiates warnings
from errors}
@item
Faces are now in a separate customization group
@end itemize

@item
Bug fixes:

@itemize
@item
Add missing customization group for syntax checker options
@end itemize

@end itemize

@node 0.12, 0.13, 0.11, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.12 (May 18, 2013)

@itemize @bullet
@item
New syntax checkers:

@itemize @bullet
@item
@ghissue{136, Ruby using @command{jruby}}
@item
@ghissue{138, Puppet}
@end itemize

@item
New features:

@itemize @bullet
@item
Highlight error expressions by default, with the new @code{sexps}
highlighting mode
@item
@ghissue{140, Automatically check syntax some time after the last change
in the buffer}
@item
Add @code{flycheck-version} to determine the installed Flycheck version
@item
Add @code{flycheck-list-errors}, mapped to @kbd{C-c ! l}, to list all
errors in a separate buffer
@end itemize

@item
Improvements:

@itemize @bullet
@item
Defer syntax checks while a buffer is reverted, to avoid race conditions
@end itemize

@item
Bug fixes:

@itemize @bullet
@item
@ghissue{136, Correctly parse syntax errors from JRuby}
@end itemize

@end itemize

@node 0.13, master, 0.12, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec 0.13 (Jun 28, 2013)

@itemize @bullet
@item
@b{Breaking changes}:

@itemize @bullet
@item
Obsolete @code{flycheck-warning-face} and @code{flycheck-error-face} in
favor @code{flycheck-warning} and @code{flycheck-error} respectively
@item
Obsolete @code{:predicate} forms in favor of @code{:predicate} functions
@item
@code{flycheck-def-config-file-var} does not automatically mark
variables as safe anymore
@end itemize

@item
New features:

@itemize @bullet
@item
Make fringe indicator faces customizable independently with
@code{flycheck-fringe-error} and @code{flycheck-fringe-warning}
@item
Improve the default faces by using underlines instead of foreground
colors, if possible
@item
@ghissue{141, Customizable error processing with
@code{flycheck-process-error-functions}}
@item
@ghissue{144, Make the delay before starting a syntax check customizable
via @code{flycheck-idle-change-delay}}
@item
@ghissue{156, Make display of errors under point customizable via
@code{flycheck-display-errors-function}}
@end itemize

@item
Improvements

@itemize @bullet
@item
Always highlight errors on top of warnings now
@item
@ghissue{141, Do not trigger syntax checks in the middle of commands}
@item
Add the current directory to load path in the @code{emacs-lisp} syntax
checker
@item
Do not longer use the @code{emacs-lisp-checkdoc} syntax checker in
Scratch buffers
@item
@ghissue{149, Do not flush temporary files onto disk}
@item
Syntax checkers may have error patterns and error parser now
@item
Predicate forms are now wrapped into functions and compiled into
functions during byte compilation
@item
Copy each message separately in @code{flycheck-copy-messages-as-kill}
@item
Mark some customizable variables as safe for file variable usage, most
notably @code{flycheck-indication-mode},
@code{flycheck-highlighting-mode} and @code{flycheck-idle-change-delay}.
@end itemize

@item
Bug fixes:

@itemize @bullet
@item
Fix error when searching for a configuration file outside a Projectile
project
@item
Do not start a syntax check before the @code{flycheck-mode-hook} was run
@item
Do not start automatic syntax checks if Flycheck Mode is disabled
@item
@ghissue{143, Defer the initial syntax check until after the current
interactive command}
@item
Correctly clean up information about running processes
@item
@ghissue{150, Fix compatibility with Emacs 24.2 and earlier}
@item
Fix version information on Emacs trunk builds
@end itemize

@end itemize
@node master, , 0.13, Changes
@comment  node-name,  next,  previous,  up
@unnumberedsec master (unreleased)

@itemize @bullet
@item
@b{Breaking changes}:

@itemize @bullet
@item
@ghissue{163, Introduce @code{flycheck-define-checker} and obsolete
@code{flycheck-declare-checker}}
@item
Remove the obsolete @code{flycheck-error-face} and
@code{flycheck-warning-face}
@item
@ghissue{176, Do not initialize packages by default in @code{emacs-lisp}
syntax checker for non-configuration files}
@end itemize

@item
New features:

@itemize
@item
@ghissue{166, List errors at point only with prefix arg to
@code{flycheck-list-errors}}
@item
@ghissue{166, Add new display function
@code{flycheck-display-errors-in-list} to display errors at point in the
error list}
@item
New @code{option-list} argument cell to pass option lists to a syntax
checker
@item
@ghissue{174, New @code{flycheck-emacs-lisp-load-path} option to
customize the @code{load-path} used by the @code{emacs-lisp} syntax
checker}
@item
@ghissue{176, New @code{flycheck-emacs-lisp-initialize-packages} option
to initialize packages in the @code{emacs-lisp} syntax checker}
@item
@ghissue{176, New @code{flycheck-emacs-lisp-package-user-dir} option to
configure the package directory for the @code{emacs-lisp} syntax
checker}
@item
New option filter @code{flycheck-option-comma-separated-list} for
options with comma separated lists as values
@end itemize

@item
New syntax checkers:

@itemize @bullet
@item
@ghissue{160, LESS}
@item
@ghissue{162, Haskell with @command{ghc}@comma{} @command{hdevtools}
and @command{hlint}}
@item
@ghissue{170, C/C++ with @command{cppcheck}}
@item
@ghissue{172, C/C++ with @command{clang}}
@end itemize

@item
Improvements:

@itemize @bullet
@item
@ghissue{157, Support Web Mode in @code{html-tidy} syntax checker}
@item
@ghissue{159, Support Rubocop 0.9 and drop support for older Rubocop
releases}
@end itemize

@item
Bug fixes:

@itemize @bullet
@item
Fix warnings about flawed definitions in @code{emacs-lisp} and
@code{emacs-lisp-checkdoc}, caused by faulty formatting of sexps
@item
@ghissue{166, Refresh error lists when pressing @kbd{g}}
@item
@ghissue{175, Do not obscure active minibuffer input when displaying
errors in the echo area}
@end itemize

@end itemize

@c Local Variables:
@c mode: texinfo
@c TeX-master: "flycheck"
@c End:
