Flycheck is extensible with new syntax checkers.  This chapter explains
how to do so, and provides examples for common use cases.

If you implement new syntax checkers, please consider @b{contributing}
these.  @xref{Contributing syntax checkers}, for more information.

@menu
* Declaration::         How to declare syntax checkers
* Error parsers::       Built-in error parsers
* Option filters::      Built-in option filters
* Examples::            Examples on how to declare syntax checkers
@end menu

@node Declaration, Error parsers, Extending, Extending
@comment  node-name,  next,  previous,  up
@section Declaration of syntax checkers

Checkers are declared with @code{flycheck-declare-checker}:

@defmac flycheck-declare-checker symbol docstring &rest properties
Declare SYMBOL as new syntax checker with PROPERTIES.

DOCSTRING provides documentation for the syntax checker.

The PROPERTIES specify the new syntax checker:

@table @code
@item :command '(@var{executable} @var{arguments}...)
A list providing the command to execute.  The command consists of an
@var{executable} specified as string in the @code{car}, and the
@var{arguments} for this executable in the @code{cdr}.  @xref{List
elements, , ,elisp}, for more information about the elements of a list.

The @var{executable} is checked for existence with
@code{executable-find} before executing the syntax checker.

In @var{arguments}, various special symbols are substituted before
executing the syntax checker:

@table @code
@item source
This symbol is substituted with the file to check.  This file is a
temporary file with the contents of the buffer to check, created in the
system's temporary directory.

If the buffer to check has a file name, the non-directory component of
the name of the temporary file will be the same as in the buffer's file
name, to support languages which enforce specific rules on the file name
(e.g. the file must be named after the containing class).

If the buffer to check has no file name, the name of the temporary file
will be random.

This symbol is the @b{preferred} way to pass the input file to your
syntax checker.

@item source-inplace
This symbol is substituted with the file to check.  This file is a
temporary file with the contents of the buffer to check, created @b{in
the same directory} as the buffer's file.  The name of the file is
random.

If the buffer has no file name, this symbol is equivalent to
@code{source}.

This symbol should be used if and only if the syntax check @b{needs
other files} from the source directory (e.g. include files in C, or
Python modules).

@item source-original
This symbol is substituted with @code{buffer-file-name}, or an empty
string, if the buffer has no file name.

This symbol is provided to @b{additionally} pass the real name of the
file to check to a syntax checker.

It should @b{never} be used as primary input to the syntax checker,
unless both @code{source} and @code{source-original} are totally not
applicable.  In this case, be sure to add a predicate to your syntax
checker that inhibits the syntax check, if the buffer has no file name,
or was modified, for otherwise the syntax check will fail or return
out-dated errors:

@lisp
:predicate #'(lambda () (and (buffer-file-name)
                             (not (buffer-modified-p)))
@end lisp

@item temporary-directory
This symbol is substituted with the path of an existing temporary
directory, which is unique on each execution of the syntax checker.

Use this symbol if you need to move files created by a syntax checker
out of the way.

See the declaration of the @code{elixir} syntax checker for an
application of this symbol.

@item (config-file @var{option} @var{variable})
This cell is substituted with a configuration file for the syntax
checker.  @var{option} is a string containing the option that specifies
a configuration file to the syntax checker tool.

@var{variable} is a symbol referring to a variable from which to obtain
the name or path of the configuration file.  @xref{Configuration}, for
more information about syntax checker configuration.  Define this
variable with @code{flycheck-def-config-file-var}.

If the configuration file is found, the cell is substituted with the
@var{option} and the absolute path to the configuration file as string.
Otherwise the cell is simply dropped from the arguments of the syntax
checker.

If @var{option} ends with a @code{=} character, @var{option} and the
absolute path to the configuration file are concatenated and given as a
single argument to the syntax checker.  Otherwise, @var{option} and the
configuration file path are given as two separate arguments.

@item (option @var{option} @var{variable} [@var{filters}])
This cell is substituted with the value of @var{variable}.  @var{option}
is a string containing the option for with to specify the value.
@var{filter} is an optional function to be applied to the value of
@var{variable} before substitution.  @xref{Option filters}, for a list
of built-in option filters.

@var{variable} is a symbol referring to a variable whose value to use.
@xref{Configuration}, for more information about syntax checker
configuration.  Define this variable with
@code{flycheck-def-option-var}.

If @var{variable} is not @var{nil} after applying @var{filter}, the cell
is substituted with the @var{option} and the value of @var{variable}
after applying @var{filter}.  Otherwise the cell is simply dropped from
the arguments of the syntax checker.

An @var{option} ending with a @code{=} character is treated like in a
@code{config-file} cell.

@item (eval @var{form})
This cell is substituted with a result of evaluating @var{form}.
@var{form} must either return a string or a list of strings, or
@code{nil} to indicate that nothing should be substituted for
@var{cell}.  In case of other return values an error is signaled.
@emph{No} further substitutions are performed, neither in @var{form}
before it is evaluated, nor in the result of evaluating FORM.
@end table

This property is @b{mandatory}.

@item :error-parser '@var{parser}
An error parser to use for parsing the output of the syntax checker.

The @var{parser} is a function symbol.  @xref{Error parsers}, for more
information about error parsers, including a list of built-in error
parsers.

Using a error parser is preferred if a syntax checker provides a
structured output format like XML or JSON.  If possible, re-use one of
the built-in error parsers listed in @ref{Error parsers}.

An error parser takes precedence over @code{:error-patterns}.  To use an
error parser together with patterns, you must manually call
@code{flycheck-parse-output-with-patterns} in your error parser to parse
with error patterns first.  You can the post-process the errors returned
by this function.

@item :error-patterns '((@var{regexp} @var{level})...)
A list of one or more error patterns to parse the output of
@code{:command}.

The @var{regexp} is a regular expression matching a single error or
warning.  The @var{level} is either @code{error} or @code{warning} and
classifies the severity of the matched error message.

Do @b{not} use error patterns if you can use an error parser.

The @var{regexp} may provide the following match groups:

@table @emph
@item Group 1
The file name.
@item Group 2
The line number.
@item Group 3
The column number.
@item Group 4
The error text.
@end table

Each of these groups is optional, however error messages without line
numbers will be ignored.  Use @b{explicitly numbered groups} to make
sure that the group numbering is correct.  @xref{Regexp Backslash, ,
,elisp}, for more information about regular expression groups.

The patterns are applied in the order of declaration to the whole output
of the syntax checker.  Output already matched by a pattern will not be
matched by subsequent patterns.  In other words, the first pattern wins.

@item :modes '@var{major-mode}
@itemx :modes '(@var{major-mode}...)
A single @var{major-mode}, or a list thereof.

@var{major-mode} is a symbol referring to a major mode.  If given the
syntax checker will only be used in buffers with any of the given major
modes.

@item :predicate #'@var{function}
@itemx :predicate #'(lambda () @var{body})))
@itemx :predicate '@var{form}
A predicate function that determines whether the syntax checker may be
used.

@var{FUNCTION} is called before each syntax check to determine whether
the syntax checker may be used for the current buffer.  If
@var{function} returns nil, the syntax checker is not used.  Of course,
you may also use a lambda expression with @var{BODY}.  @xref{Lambda
Expression, , , elisp}, for more information on lambda expression.

Alternatively, you may also specify a @var{form} which is then evaluated
to determine whether the syntax checker may used.  However, this usage
is obsolete.

If @var{:modes} is given, @var{form} is only called if the major mode
matches.  Otherwise the syntax checker is not used.

@item :next-checker '(@var{item}...)
A list of syntax checker to run after this syntax checker.

Each @var{item} is either a single syntax checker symbol, or a cons cell
@code{(@var{predicate} . @var{checker})}.  Each @var{item} is tried on
the order of declaration.

If the @var{item} is a syntax checker symbol, determine whether it is
usable @b{and} registered (i.e. contained in @code{flycheck-checkers}).
If so start a new syntax check with that syntax checker, and merged its
results with the results of this syntax checker.  If not, try the next
@var{item}.

If @var{item} is a cons cell, @var{predicate} specifies whether to run
the @var{checker} depending on the results of this syntax checker:

@table @code
@item no-errors
The @var{checker} is only used if this syntax checker resulted in no
errors at all.
@item warnings-only
The @var{checker} is only used if this syntax checker did not result in
error messages of severity @code{error}.
@end table

If the predicate matches, and @var{checker} is usable and registered,
start a new syntax checker with @var{checker} and merged its results
with the results of this syntax checker.  If not, try the next
@var{item}.

If there is no further @var{item}, finish the syntax check.
@end table

At least on of @code{:modes} and @code{:predicate} must be present.  If
both are present, both must match for the syntax checker to be used.

Either @code{:error-patterns} or @code{:error-parser} must be present.
If both are present, an error is signaled.
@end defmac

A syntax checker declared with @code{flycheck-declare-checker} is
already suitable for manual checker selection with
@code{flycheck-select-checker}.  For automatic selection the syntax
checker must be registered by adding it to @code{flycheck-checkers}.
@xref{Selection}.

@defmac flycheck-def-config-file-var @var{symbol} @var{checker} @
  &optional @var{filename}
Define @var{symbol} as configuration file variable for a syntax
@var{checker}, with a default value of @var{filename}.

@var{symbol} is declared as customizable, buffer-local variable using
@code{defcustom}, to provide a configuration file for the given syntax
@var{checker}.  The variable has the customization type @code{string},
and gets a comprehensive docstring, including a reference to
@var{checker}.

@var{filename} is used as initial value for the variable.  If omitted,
the initial value is nil.

Use this macro together with the @code{config-file} cell in the command
of a syntax checker.
@end defmac

@defmac flycheck-def-option-var @var{symbol} @var{initial-value} @
  @var{checker} &optional @var{custom-args}
Define @var{symbol} as option variable for a syntax @var{checker}, with
the given @var{initial-value}.

@var{symbol} is declared as customizable variable, buffer-local variable
using @code{defcustom}, to provide an option for the given syntax
@var{checker}.  @var{symbol} gets a comprehensive docstring, including a
reference to @var{checker}.

@var{custom-args} are forwarded to @code{defcustom}.  Declare the
customization type here.

Use this macro together with the @code{option} cell in the command of a
syntax checker.
@end defmac

@node Error parsers, Option filters, Declaration, Extending
@comment  node-name,  next,  previous,  up
@section Error parsers

Syntax checkers may use more sophisticated error parsing by using the
@code{:error-parser} property.  @xref{Declaration}.

Flycheck provides the following error parsers for use by syntax
checkers:

@table @code
@item flycheck-parse-with-patterns
Parse output with the @code{:error-patterns} of the syntax checker.
@item flycheck-parse-checkstyle
Parse XML output similar to @uref{http://checkstyle.sourceforge.net/,
Checkstyle}.
@end table

You may also define your own error parsers.  An error parser is a
function that takes three arguments:

@table @var
@item output
The complete output of the syntax checker as string.
@item checker
A symbol denoting the executed syntax checker.
@item buffer
A buffer object referring to the buffer that was syntax-checked.
@end table

The function shall return a list of Flycheck errors.  @xref{Error API},
for more information about Flycheck errors.

Flycheck provides some utility functions to implement error parsers.
@xref{Error parser API}.

@node Option filters, Examples, Error parsers, Extending
@comment  node-name,  next,  previous,  up
@section Option filters

Flycheck provides the following built-in option filters for use with the
@code{option} cell:

@table @code
@item flycheck-option-int
An integral option that handles @code{nil} correctly (unlike
@code{number-to-string}).
@end table

@node Examples,  , Option filters, Extending
@comment  node-name,  next,  previous,  up
@section Examples of syntax checkers

@menu
* Simple example::              How to declare basic syntax checkers
* Predicate example::           How to control syntax checker usage
* Configuration example::       How to configure syntax checkers
* Chaining example::            How to execute more than one syntax checker
@end menu

@node Simple example, Predicate example, Examples, Examples
@comment  node-name,  next,  previous,  up
@subsection Basic syntax checkers

As explained in the previous chapter @ref{Extending} a syntax checker is
declared with @code{flycheck-declare-checker}.

We will use this function to declare a syntax checker using the
CodeSniffer utility for the PHP programming language:

@lisp
(flycheck-declare-checker php-phpcs
  "A PHP syntax checker using PHP_CodeSniffer.

See URL `http://pear.php.net/package/PHP_CodeSniffer/'."
  :command '("phpcs" "--report=checkstyle" source)
  :error-parser 'flycheck-parse-checkstyle
  :modes 'php-mode)
@end lisp

First we specify the @code{:command} to execute.  The first element of
the command list is the name of the executable, @command{phpcs} in our
case.  This command is checked for existence with @code{executable-find}
before using this syntax checker.  If the command does not exist, the
syntax checker is @emph{not} used.

The executable is following by the arguments, in this case some options
and the symbol @code{source}.  This symbol is replaced with the file to
check.  This file is a temporary file created in the system temporary
directory and containing the contents of the buffer to check.

Next we specify how to parse the output of the syntax checker.  PHP
CodeSniffer provides an option to output errors in an XML format similar
to the Java tool Checkstyle, so we use the built-in @emph{error parser}
@code{flycheck-parse-checkstyle} to parse the output.

Eventually we enable the syntax checker in PHP editing modes.

If the syntax checker does not provide any sort of structured output
format, we have to parse the error messages from the textual output.  To
do so, we can use @emph{error patterns}, like in the Pylint syntax
checker for the Python programming language:

@lisp
(flycheck-declare-checker python-pylint
  "A Python syntax and style checker using the pylint utility.

See URL `http://pypi.python.org/pypi/pylint'."
  :command '("epylint" source-inplace)
  :error-patterns
  '(("^\\(?1:.*\\):\\(?2:[0-9]+\\): Warning (W.*): \\(?4:.*\\)$" warning)
    ("^\\(?1:.*\\):\\(?2:[0-9]+\\): Error (E.*): \\(?4:.*\\)$" error)
    ("^\\(?1:.*\\):\\(?2:[0-9]+\\): \\[F\\] \\(?4:.*\\)$" error))
  :modes 'python-mode)
@end lisp

Again, there is a @code{:command}, however we use the
@code{source-inplace} symbol this time.  This symbol causes the
temporary file to be created in the same directory as the original file,
making information from the source code tree available to the syntax
checker.  In case of Pylint, these are the Python packages from the
source code tree.

Next we give the list of @emph{error patterns} to parse errors.  These
patterns extract the error location and the error message from the
output of @command{epylint}.  An error pattern is a list containing a
regular expression with match groups to extract the error information,
and an error level (either @code{warning} or @code{error}).

Eventually we enable the syntax checker in @code{python-mode}.

@node Predicate example, Configuration example, Simple example, Examples
@comment  node-name,  next,  previous,  up
@subsection Syntax checkers with predicates

In the previous examples the syntax checkers were specific to certain
major modes.  However, this is not always the case.  For instance, GNU
Emacs provides a single mode only for shell scripting in various Shell
languages.  A syntax checker for a specific shell must check whether the
edited shell script is written for the right shell:

@lisp
(flycheck-declare-checker zsh
  "A Zsh syntax checker using the zsh executable.

See URL `http://www.zsh.org/'."
  :command '("zsh" "-n" "-d" "-f" source)
  :error-patterns '(("^\\(?1:.*\\):\\(?2:[0-9]+\\): \\(?4:.*\\)$" error))
  :modes 'sh-mode
  :predicate '(eq sh-shell 'zsh))
@end lisp

This syntax checker for the Zsh shell is enabled in @code{sh-mode} as
specified by @code{:modes}, however it specifies an additional
@code{:predicate} to determine whether the right shell is in use.  Hence
this syntax checker is only used if a Zsh shell scripting is being
edited in @code{sh-mode}, but not if a Bash or POSIX Shell script is
being edited.

A syntax checker may even go as far as not having @code{:modes} at all.
For instance, there is no special JSON mode, but syntax checking JSON is
still desirable.  Hence a JSON syntax checker may use the
@code{:predicate} to check the file extension:

@lisp
(flycheck-declare-checker json-jsonlint
  "A JSON syntax and style checker using jsonlint.

See URL `https://github.com/zaach/jsonlint'."
  :command '("jsonlint" "-c" "-q" source)
  :error-patterns
  '(("^\\(?1:.+\\)\: line \\(?2:[0-9]+\\), col \\(?3:[0-9]+\\), \\(?4:.+\\)$"
     error))
  :predicate '(and buffer-file-name
                   (string= "json" (file-name-extension buffer-file-name)))))
@end lisp

This syntax checker is now used whenever a file ends with .json,
regardless of the major mode.

@node Configuration example, Chaining example, Predicate example, Examples
@comment  node-name,  next,  previous,  up
@subsection Configuration files for syntax checkers

Some syntax checkers can be configured using configuration files given
by an option.  Flycheck provides built-in support to handle such
configuration files:

@lisp
(flycheck-def-config-file-var flycheck-jshintrc javascript-jshint ".jshintrc")

(flycheck-declare-checker javascript-jshint
  "A JavaScript syntax and style checker using jshint.

See URL `http://www.jshint.com'."
  :command '("jshint" "--checkstyle-reporter"
             (config-file "--config" flycheck-jshintrc) source)
  :error-parser 'flycheck-parse-checkstyle
  :modes '(js-mode js2-mode js3-mode))
@end lisp

As you can see, we declare a syntax checker for Javascript, using the
@command{jshint} utility.  This utility accepts a configuration file via
the @option{--config} option.

To use a configuration file with jshint, we first declare the variable
@code{flycheck-jshintrc} that provides the name of the file, as
explained in @ref{Configuration}.

In the @code{:command} we use a @code{config-file} element to pass the
configuration file to the syntax checker.  If the configuration file is
found, its path will be passed to the syntax checker, using the option
specified after the @code{config-file} symbol.  Otherwise the whole
element is simply omitted from the command line.

Some Syntax checkers can also be configured using options passed on the
command line.  Flycheck supports this case, too.  We will use this
facility to extend the PHP CodeSniffer syntax checker from the
@ref{Simple example} with support for coding standards:

@lisp
(flycheck-def-option-var flycheck-phpcs-standard nil phpcs
  "The coding standard for PHP CodeSniffer."
  :type '(choice (const :tag "Default standard" nil)
                 (string :tag "Standard name" nil)))
(put 'flycheck-phpcs-standard 'safe-local-variable #'stringp)

(flycheck-declare-checker php-phpcs
  "A PHP syntax checker using PHP_CodeSniffer."
  :command '("phpcs" "--report=checkstyle"
             (option "--standard=" flycheck-phpcs-standard)
             source)
  :error-parser 'flycheck-parse-checkstyle
  :modes 'php-mode)
@end lisp

The syntax checker is pretty much the same as before, except that a new
element was added to @code{:command}.  This element passes the value of
the new option variable @code{flycheck-phpcs-standard} to the syntax
checker.  This variable is declared with the special macro
@code{flycheck-def-option-var} at the beginning.


@node Chaining example,  , Configuration example, Examples
@comment  node-name,  next,  previous,  up
@subsection Chaining syntax checkers

For many languages, more than a single syntax checker is applicable.
For instance, Emacs Lisp can be checked for syntactic corrections with
the byte code compiler, and for adherence to the Emacs Lisp
documentation style using Checkdoc.  PHP, too, can be syntax checked
with the PHP parser, and verified against coding styles using PHP
CodeSniffer.

To support such cases, syntax checkers can be @dfn{chained} using the
@code{:next-checkers}.  The standard PHP syntax checker uses this to
run PHP CodeSniffer if there are no syntax errors:

@lisp
(flycheck-declare-checker php
  "A PHP syntax checker using the PHP command line.

See URL `http://php.net/manual/en/features.commandline.php'."
  :command '("php" "-l" "-d" "error_reporting=E_ALL" "-d" "display_errors=1"
             "-d" "log_errors=0" source)
  :error-patterns
  '(("\\(?:Parse\\|Fatal\\|syntax\\) error[:,] \\(?4:.*\\) in \\(?1:.*\\) on line \\(?2:[0-9]+\\)"
    error))
  :modes 'php-mode
  :next-checkers '((warnings-only . php-phpcs)))
@end lisp

Now PHP CodeSniffer will check the coding style, whenever a PHP syntax
check did not result in any errors, if PHP CodeSniffer syntax checker is
usable @emph{and} registered.

@c Local Variables:
@c mode: texinfo
@c TeX-master: "flycheck"
@c End:
