Flycheck (aka ``Flymake done right'') is a modern on-the-fly syntax
checking extension for GNU Emacs 24 withL

@itemize @bullet
@item
ready-to-use syntax checkers for a bunch of languages,
@item
easy customization,
@item
a comprehensive manual,
@item
a dead simple, declarative API to create new syntax checkers,
@item
major-mode based selection of syntax checkers,
@item
multiple syntax checkers per buffer,
@item
optional error list popup,
@item
a ``doesn't get in your way'' guarantee,
@item
and a clean, concise and understandable implementation with decent test
coverage.
@end itemize

@ifhtml
@noindent
And this is how it looks in action, using the awesome
@uref{https://github.com/bbatsov/solarized-Emacs, solarized-light} color theme:
@center @image{screenshot,,,Flycheck in action}
@end ifhtml

@menu
* Features::                    What Flycheck can do for you
* Installation::                How to install Flycheck in your GNU Emacs 24
* Activation::                  How to activate Flycheck for on-the-fly syntax
                                 checking
@end menu

@node Features, Installation, Introduction, Introduction
@comment  node-name,  next,  previous,  up
@section Features

@itemize @bullet
Automatic on-the-fly syntax checking while editing
@item
Fully automatic selection of the syntax checker
@item
Optional manual selection of a syntax checker with
@code{flycheck-select-checker} at @kbd{C-c ! s}
@item
Built-in syntax checkers for:
@itemize @bullet
@item
C/C++ (using @command{clang} and @command{cppcheck})
@item
CoffeeScript (using @command{coffeelint})
@item
CSS (using @command{csslint}))
@item
Elixir (using @command{elixirc})
@item
Emacs Lisp (using the byte compiler and CheckDoc)
@item
Erlang (using @command{erlc})
@item
Go (using @command{gofmt}, @command{go build} and @command{go test})
@item
Haml
@item
Haskell (using @command{ghc}, @command{hdevtools} and @command{hlint})
@item
HTML (using @command{tidy})
@item
Javascript (using @command{jshint})
@item
JSON (using @command{jsonlint})
@item
LESS (using @command{lessc})
@item
Lua
@item
Perl
@item
PHP (using the PHP Command Line and PHP CodeSniffer)
@item
Puppet (using @command{puppet parser} and @command{puppet-lint})
@item
Python (using @command{flake8}, @command{pylint}, or @command{pyflakes})
@item
Ruby (using @command{rubocop}, @command{ruby} or @command{jruby})
@item
Rust (using @command{rustc})
@item
RST (ReStructuredText, using Docutils)
@item
Sass
@item
Scala
@item
SCSS
@item
Shell scripts (using Bash, Dash, or Zsh depending on the type of shell
script)
@item
TeX/LaTeX (using @command{chktex} or @command{lacheck})
@item
XML (using @command{xmlstarlet})
@end itemize
@item
Nice error indication and highlighting
@item
Easy customization
@item
Syntax checker configuration with project-specific configuration files
and options
@item
Error navigation with @code{next-error} and @code{previous-error}
@item
Error list with @code{flycheck-list-errors} at @kbd{C-c ! l}
@item
Easy declarative API to define new syntax checkers
@item
Error parsers for structured markup formats (e.g. Checkdoc XML)
@end itemize

@subsection 3rd party extensions

The following extensions provide additional cool features for Flycheck:

@itemize @bullet
@item
@uref{https://github.com/syl20bnr/flycheck-color-mode-line,
flycheck-color-mode-line.el} colors the mode line according to the
Flycheck status.

@end itemize

@node Installation, Activation, Features, Introduction
@comment  node-name,  next,  previous,  up
@section Installation

Install the ELPA package from @uref{http://melpa.milkbox.net, MELPA} or
@uref{http://marmalade-repo.org/, Marmalade} using @kbd{M-x
package-install RET flycheck}.  The former is the @emph{recommended}
repository.

Neither of these repositories is included in GNU Emacs by default.  You
need to enable these repositories explicitly.  For instance, to add the
MELPA repository, add the following code to @file{init.el}:

@lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)
@end lisp

Flycheck supports GNU Emacs 24.2 and newer on Linux, OS X and any other
decent flavor of Unix.  It should work with GNU Emacs 24.1, too, but it
is not tested against this version of Emacs.

Flycheck does not support Windows, but tries to be compatible with it.
You may try to use Flycheck on Windows.  It should mostly work, but
expect problems and issues.  Pull requests which improve Windows
compatibility are welcome.

Flycheck also does not support GNU Emacs 23 and other flavors of Emacs
(e.g. XEmacs, Aquamacs, etc.).  Don't try, it will @emph{not} work.

Most checkers depend on external tools to perform the actual syntax
checking.  Use @code{flycheck-describe-checker} to get help about a
syntax checker and its dependencies.

@node Activation,  , Installation, Introduction
@comment  node-name,  next,  previous,  up
@section Activation

Once installed, enable Flycheck mode with @kbd{M-x flycheck-mode}.  To
automatically enable Flycheck in all buffers, in which it can be used,
add the following to your @file{init.el} file:

@lisp
(add-hook 'after-init-hook #'global-flycheck-mode)
@end lisp

@c Local Variables:
@c mode: texinfo
@c TeX-master: "flycheck"
@c End:
