- name: Add Rust repository
  apt_repository: repo='ppa:hansjorg/rust' state=present
  sudo: true
- name: Remove Rust Nightly
  apt: name='rust-nightly' state=absent purge=yes
  sudo: true
- name: Remove Rust 1.0 beta
  apt: name='rust-1.0.0-beta' state=absent purge=yes
  sudo: true
- name: Install Rust stable
  apt: name='rust-stable' state=latest install_recommends=false
  sudo: true
- name: Use Rust stable as default
  alternatives: name=rustc path='/usr/lib/rust/rust-stable/bin/rustc'
  sudo: true
